name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 缓存 pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: "setup pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "setup node"
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      # 缓存 node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: "Install"
        run: "pnpm install"

      # 压缩图片
      - name: "图片压缩"
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '80'
          pngQuality: '80'
          webpQuality: '80'
          ignorePaths: 'node_modules/**'
          compressOnly: true

      - name: "MarkdownLint Check"
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: 'docs*/**/*.md'

      - name: "Build"
        run: "pnpm run build"